### PR TITLE
Fix conflicting declarations with scoped @Provides functions

### LINKED ISSUE #174: Conflicting declarations for scoped `@Provides` functions with parameterized return type
If I have:

```
import me.tatarka.inject.annotations.Inject
import me.tatarka.inject.annotations.Provides
import me.tatarka.inject.annotations.Component
import me.tatarka.inject.annotations.Scope

@Scope annotation class MyScope

@MyScope @Component abstract class MyComponent {
  abstract val foo: Foo
 
  @MyScope @Provides protected fun t1() = T<Int>()
 
  @MyScope @Provides protected fun t2() = T<String>()
}

class T<T>

@MyScope @Inject class Foo(
  private val t1: T<Int>,
  private val t2: T<String>,
  private val bar: Bar
)

@MyScope @Inject class Bar(
  private val t1: T<Int>,
  private val t2: T<String>
)
```

then the generated properties for both are named `_t`.

### PR DESCRIPTION
**Pull request by eygraber**
- If multiple scoped @Provides functions have the same return type with different type args, the generated properties will have the same name
  - This causes conflicting declaration errors while compiling
  - To fix that, the type args are included in property name generation

Fixes #174

### CODE REVIEW

File: kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/RoundsTest.kt [hunk 1]
```diff
@@ -263,4 +265,45 @@ class RoundsTest {
             doesNotContain("Cannot provide", "as it is already provided")
         }
     }
-}
\ No newline at end of file
+
+  @ParameterizedTest
+  @EnumSource(Target::class)
+  fun scoped_provides_funs_that_have_the_same_return_type_with_different_type_args_does_not_conflict(target: Target) {
```
Comment (evant) [inline kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/RoundsTest.kt:271]: Since this is a happy-path test, it can go it integration-tests instead.

**Review by evant — COMMENTED** [review]
Thanks! 1 comment about the test but other than that looks good!

File: kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/RoundsTest.kt (hunk 1 above)
Comment (eygraber) [reply kotlin-inject-compiler/test/src/test/kotlin/me/tatarka/inject/test/RoundsTest.kt]: Updated

**Review by evant — APPROVED** [review]
